site_name: Skye Mastercard® Documentation
site_dir: 'skyedocs'
nav:
- Home: index.md
- E-commerce Integration:
   - Shopify: ecommerce/shopify.md
   - WooCommerce: ecommerce/woocommerce.md
   - Magento 1: ecommerce/magento_1.md
   - OpenCart: ecommerce/opencart.md
- Best Practice Integration: best_practice_integration.md
- Widgets:
   - Price-info Widget: widgets/price_info.md
   - Calculator Widget: widgets/calculator_widget.md
   - Widget Installation:
      - Generic Installation: widgets/installation.md
      - On Shopify: widgets/price-info/shopify.md
      - On Magento 1: widgets/price-info/magento_1.md 
      - On OpenCart 3: widgets/price-info/opencart_3.md
- Developer Resources:
   - Introduction: developer_resources/introduction.md
   - Checkout Process: developer_resources/checkout_process.md
   - Checkout Web Services: developer_resources/checkout_web_service.md
   - Sample test page: developer_resources/sample_curl.md   

theme: 
  name: null
  custom_dir: material
  language: en
  feature:
   tabs: false
  palette:
   primary:
   accent:
  font:
   text: Roboto
   code: Roboto Mono
  favicon: assets/images/favicon.png
  logo:
   icon: "\uE80C"
  include_search_page: false
  search_index_only: true
  static_templates:
  - 404.html
extra_css: [css/jquery.modal.min.css, css/custom.css]
extra_javascript: [js/jquery.modal.js]
extra:
   domain: skyecard.com.au
   domain_postfix: .com.au
   currency_abbr: AUD
   country_abbr: AU
   address_city: Adelaide
   address_street_1: 97 Pirie St
   address_street_2: Level 6
   address_phone_number: 0400 000 000
   address_state_abbr: SA
   address_post_code: 5000
   country: Australia
   merchantID_for_curl: 30199250
   signature_for_curl: 5390d3249610b40b146ada45d46493895dbad0e7ca05daa7df42e6bd0cfc203f
   payment_desc: ''
   max_purchase: 2100
